sudo: required
services :
    - docker
before_install :
    - docker build -t deniswoeffray/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true deniswoeffray/docker-react npm run test